server:
  port: 8200
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8000/eureka
spring:
  application:
    name: order-openfeign
# 设置 feign客户端超时时间（openFeign默认支持ribbon）
ribbon:
  # 指的是建立连接所用的时间 ，适用于网络状况正常的情况下。两端连接所用的时间
  ReadTimeout: 5000
  # 指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000


logging:
  level:
    # feign日志以什么级别监控哪个接口
    com.xbb.feign.PaymentFeignService: debug